version: '2'

services:
  app:
    image: book-store:initial
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rest_application
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - FLYWAY_ENABLED=true
    volumes:
      - ./logs:/var/log/webapp

  db:
    image: postgres:13.1-alpine
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=rest_application
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  db: