jwt:
  secret:
    access: rJLz/MUJ9f3clEZ2IutTNJfP9KOj7mZ+CIsirr6eDNoZGkHB/8wvemIewPC+3UG9Kfq7DO66vT0KS3sEbYlIVA==
    refresh: NQ0mHsK2/a9ep7VlHvsIgedgiVC5XW1CXhPU0H6c7xNgjpEeHKMqNbU1wj8T/+HGwWzSJtLXUQVRrCpYzLnG5Q==

spring:
  jpa:
    open-in-view: false
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/rest_application
    username: root
    password: 123
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
name: ${name:development}
environment: development
servers:
  - dev.rest.app.com

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/rest_application
    username: root
    password: 123
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
name: ${name:test}
environment: test
servers:
  - test.rest.app.com

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/rest_application
    username: root
    password: 123
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
name: ${name:production}
environment: production
servers:
  - rest.app.com


#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE