-- AUTHORITIES
CREATE TABLE IF NOT EXISTS authorities
(
    user_id       BIGINT NOT NULL,
    authority_set VARCHAR(255)
);

ALTER TABLE authorities
    ADD CONSTRAINT fk_authority_on_user FOREIGN KEY (user_id) REFERENCES users (user_id);


-- USERS
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(50)                             NOT NULL,
    password VARCHAR(50)                             NOT NULL,
    enabled  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);